name: Covid19-Cases

on: 
  schedule:
    - cron: "15 9 * * *"
  workflow_dispatch:

jobs:
  cases:
    name: Cases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Stats
        uses: xHyroM/covid19-stats/.github/actions/cases@master
        with:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
        env:
          apiToken: ${{secrets.apiToken}}
